myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path('',views.index,name= 'index'),
    path('book/<int:book_id>/',views.detail,name = 'detail'),
    path('add/',views.add_book,name= 'add_book'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name= 'delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views,urls
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    def __str__(self):
        return self.name
    
    
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=100)
    price = models.IntegerField()
    book_image = models.ImageField(default='default.jpg',upload_to='book_image/')
    

myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:

        model = Book
        fields = ['name','desc','book_image','price']
    

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Book
from .forms import BookForm
# Create your views here.

def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list':book_list
        }
    return render(request,'myapp/index.html',context)

def detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request,'myapp/detail.html',{'book':book})

def add_book(request):
    if(request.method=="POST"):
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']
        
        book = Book(name=name,desc=desc,price=price,book_image=book_image)
        book.save()
    return render(request,'myapp/add_book.html')

def update(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance = book)
    if form.is_valid():
        form.save()

        return redirect('/')
    return render(request,'myapp/edit.html',{'form':form,'book':book})

def delete(request,id):
    if(request.method=="POST"):
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request,'myapp/delete.html',)

myapp/templates/myapp/add_book.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" id="name" placeholder="enter name of the book">
    <input type="text" name="desc" id="desc" placeholder="enter description of book">
    <input type="text" name="price" id="price" placeholder="enter the price">
    <input type="file" name="book_image" id= "book_image"><br>
    <input type="submit" name= "" id= "">
</form>

myapp/templates/myapp/base.html
{% load static %}

<!Doctype html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{%static 'myapp/style.css'%} -->

</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
            <!-- <img src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top"> -->
             Online BookStore
            </a>
      </div>
    </nav>
    
    {% block body %}
    
    {% endblock %}
   


</body>
</html>

myapp/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this book
    <input type="submit">
</form>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html'%}

{% block body %}

    <div class="container">
        <div class ="row">
            <div class="col-md-6">
                
                <img width = "300",height = "300" src="{{book.book_image.url}}">
            </div>
            <div class="col-md-6">
                <h1>{{book.name}}</h1>
                <h4>{{book.desc}}</h4>
                <h5>{{book.price}}</h5>
                <a class = "btn btn-warning" href = "{% url 'myapp:update' book.id %}">update now</a>
                <a class = "btn btn-danger" href = "{% url 'myapp:delete' book.id %}">delete now</a>
            </div>
        </div>
    </div>
    
   
    

{% endblock %}

myapp/templates/myapp/edit.html
<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form> 

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body %}
<div class="card">
    {% for book in book_list %}
    <div class="card-header">
      BOOK
    </div>
    <div class="card-body">
        <img src="{{book.book_image.url}}" width="100" height="100">
      <h5 class="card-title">{{book.name}}</h5>
      <a href = ></a><br>
      <p class="card-text">price={{book.price}}</p>
      <a  class="btn btn-primary"href="{% url 'myapp:detail' book.id %}">Go to details </a>
    </div>
    {% endfor %}
  </div>
        

            <div>
             <a class="btn btn-warning" href = "{% url 'myapp:add_book' %}">add new</a>
            </div>
{% endblock %}